<template>
  <div>
    <h2>分类11111111111111111</h2>
    <div class='wrapper' ref='wrapper'>
      <ul class='content'>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>3</li>
        <li>4</li>
        <li>546</li>
        <li>57</li>
        <li>67</li>
        <li>6</li>
        <li>5</li>
        <li>5</li>
        <li>5</li>
        <li>5</li>
        <li>5</li>
        <li>5</li>
        <li>5</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>7</li>
        <li>89</li>
        <li>8</li>
        <li>9</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>7</li>
        <li>8</li>
        <li>7</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>8</li>
        <li>78</li>
        <li>7</li>
        <li>7</li>
        <li>6</li>
        <li>7</li>
        <li>67</li>
        <li>7</li>
        <li>9</li>
        <li>5</li>
        <li>6</li>
        <li>6</li>
        <li>7</li>
        <li>7</li>
        <li>7</li>
        <li>7</li>
        <li>7</li>
        <li>56</li>
        <li>6</li>
        <li>6</li>
        <li>5</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
        <li>6</li>
      </ul>
    </div>
  </div>
</template>
<script>
  import BScroll from 'better-scroll'
  export default{
    name:'Category',
    data(){
      return {
        scroll:null,
      }
    },
    //template挂载完毕
    mounted(){
      this.scroll=new BScroll(document.querySelector('.wrapper'),{
        probyType:3,
        pullUpLoad:true,
      }),
     /*  this.scroll=new BScroll(this.$refs.wrapper,{
        probyType:3,
      }),*/
      this.scroll.on('scroll', (position) => {
         //console.log(position);
       }),
       this.scroll.on('pullingUp', () => {
         console.log('上拉加载更多');
       })
    }
  }
</script>
<style scoped>
.wrapper{
  height:300px;
  background-color:cadetblue;
  overflow:hidden;
}
</style>